#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Path variables
export GOPATH=$HOME/Developer/go
export GOROOT=/usr/local/go
export PATH=$PATH:$HOME/Developer/go/bin
export PATH=$PATH:/usr/local/go/bin
#export PATH="\$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
#export PATH=$PATH:/Users/valdemiro.vieira/Library/Android/sdk/platform-tools
#export PATH=$PATH:/Users/valdemiro.vieira/Library/Android/sdk/tools/proguard/bin

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
